#!/usr/bin/env python3
"""
Crawl the EngineerPro FAQ page and emit a JS data file the static site embeds.

Output: src/assets/faqs-data.js
        window.FAQS = [ { question, html, plain }, ... ]

Re-run with:  python3 scripts/crawl_faqs.py
"""
from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

from bs4 import BeautifulSoup, Comment, Tag

URL = "https://engineerprogurus.com/blogs/faqs"
BASE = "https://engineerprogurus.com"
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 "
    "(KHTML, like Gecko) Version/17.5 Safari/605.1.15"
)
OUT = Path(__file__).resolve().parent.parent / "src" / "assets" / "faqs-data.js"

KEEP_ATTRS = {"href", "target", "rel"}
DROP_TAGS = {"script", "style", "noscript", "ins", "i"}


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read().decode("utf-8", errors="replace")


def clean_node(node: Tag) -> None:
    # drop disallowed tags
    for t in DROP_TAGS:
        for n in node.find_all(t):
            n.decompose()
    # drop HTML comments
    for c in node.find_all(string=lambda s: isinstance(s, Comment)):
        c.extract()
    # unwrap span/font/u — they're usually editor garbage
    for tag_name in ("span", "font", "u"):
        for n in list(node.find_all(tag_name)):
            n.unwrap()
    # strip junk attrs from every element
    for n in node.find_all(True):
        for attr in list(n.attrs.keys()):
            if attr not in KEEP_ATTRS:
                del n.attrs[attr]
        # absolutise links + open in new tab
        if n.name == "a":
            href = n.get("href") or ""
            if href.startswith("/"):
                n["href"] = BASE + href
            if (n.get("href") or "").startswith("http"):
                n["target"] = "_blank"
                n["rel"] = "noopener"


def inner_html(node: Tag) -> str:
    html = "".join(str(c) for c in node.children)
    html = re.sub(r"&nbsp;", " ", html)
    return re.sub(r"\s+", " ", html).strip()


def main() -> int:
    print(f"→ fetching {URL} …")
    soup = BeautifulSoup(fetch(URL), "html.parser")
    items = soup.select(".item-faq")
    print(f"  found {len(items)} FAQ items")

    records = []
    for it in items:
        header = it.select_one(".header-faq")
        body = it.select_one(".body-faq")
        if not header or not body:
            continue
        clean_node(header)
        clean_node(body)
        question = header.get_text(" ", strip=True)
        question = re.sub(r"\s+", " ", question)
        html = inner_html(body)
        plain = body.get_text(" ", strip=True)
        records.append({"question": question, "html": html, "plain": plain})

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/crawl_faqs.py — do not edit by hand.\n"
        f"// Source: {URL}\n"
        f"window.FAQS = {payload};\n",
        encoding="utf-8",
    )
    print(f"✓ wrote {len(records)} FAQs → {OUT.relative_to(OUT.parent.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
