#!/usr/bin/env python3
"""
Crawl the EngineerPro Substack podcast archive via the public API and emit a JS
data file the static site embeds at build time.

Output: src/assets/podcasts-data.js
        window.PODCASTS = [ { title, slug, url, series, date, duration, blurb }, ... ]

Re-run with:  python3 scripts/crawl_podcasts.py
"""
from __future__ import annotations

import html as html_lib
import json
import re
import sys
import urllib.request
from pathlib import Path

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15"
API = "https://engineerprovn.substack.com/api/v1/archive?sort=new&type=podcast&offset={offset}&limit={limit}"
OUT = Path(__file__).resolve().parent.parent / "src" / "assets" / "podcasts-data.js"


def fetch_json(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.loads(r.read())


def fetch_all() -> list[dict]:
    out: list[dict] = []
    limit = 12
    offset = 0
    while True:
        chunk = fetch_json(API.format(offset=offset, limit=limit))
        if not chunk:
            break
        out.extend(chunk)
        if len(chunk) < limit:
            break
        offset += limit
        if offset >= 300:  # safety stop
            break
    return out


def fmt_date(iso: str) -> str:
    if not iso:
        return ""
    # "2026-05-23T..." -> "May 23, 2026"
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})", iso)
    if not m:
        return iso
    y, mo, d = m.groups()
    months = [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ]
    return f"{months[int(mo) - 1]} {int(d)}, {y}"


def fmt_duration(seconds: int) -> str:
    seconds = int(seconds or 0)
    if seconds <= 0:
        return ""
    mm, ss = divmod(seconds, 60)
    hh, mm = divmod(mm, 60)
    return f"{hh}:{mm:02d}:{ss:02d}" if hh else f"{mm:02d}:{ss:02d}"


def derive_series(title: str) -> str:
    t = title.lower()
    if "coffee with lam" in t and "hieu" in t:
        return "Coffee with Lam & Hieu"
    if "coffee with lam" in t:
        return "Coffee with Lam"
    if "low level design" in t or "machine coding" in t:
        return "Big Tech Interview Styles"
    if "system design" in t or "behaviour" in t:
        return "Interview Prep"
    if "engineer pro" in t or "engineerpro" in t or "học viên" in t:
        return "Hành trình học viên"
    if "thắc mắc" in t or "giải đáp" in t:
        return "Q&A Lộ trình"
    return "EngineerPro Podcast"


def strip_html(s: str) -> str:
    s = re.sub(r"<[^>]+>", " ", s or "")
    s = html_lib.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def to_record(post: dict) -> dict:
    return {
        "title": (post.get("title") or "").strip(),
        "slug": post.get("slug") or "",
        "url": post.get("canonical_url") or "",
        "series": derive_series(post.get("title") or ""),
        "date": fmt_date(post.get("post_date") or ""),
        "duration": fmt_duration(post.get("podcast_duration")),
        "blurb": strip_html(post.get("description") or post.get("subtitle") or "")[:240],
    }


def main() -> int:
    print("→ fetching podcast archive via Substack API …")
    posts = fetch_all()
    print(f"  got {len(posts)} items from API (podcast type)")
    # Keep only real audio episodes — posts WITHOUT podcast_duration are
    # written newsletter articles that happen to be in the podcast feed.
    posts = [p for p in posts if (p.get("podcast_duration") or 0) > 0]
    records = [to_record(p) for p in posts]
    records = [r for r in records if r["title"] and r["url"]]
    print(f"  → {len(records)} audio episodes (filtered out written posts)")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/crawl_podcasts.py — do not edit by hand.\n"
        "// Source: engineerprovn.substack.com/podcast/archive (Substack API)\n"
        f"window.PODCASTS = {payload};\n",
        encoding="utf-8",
    )
    rel = OUT.relative_to(OUT.parent.parent.parent)
    print(f"✓ wrote {len(records)} podcasts → {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
