#!/usr/bin/env python3
"""
Post-process VI chapter HTML — terminology consistency + common MT fixes.
Run after translate_system_design.py; safe to re-run (idempotent).

Policy (keep English): standard System Design / Big Tech interview terms stay in
English when a literal Vietnamese translation hurts clarity — e.g. Components,
database, worker, object store, news feed, friends, topic/partition/broker.
Fix only wrong MT artifacts; do not Vietnamese-ize established jargon.

  python3 scripts/review_system_design.py
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VI_DIR = os.path.join(ROOT, "src", "assets", "content", "system-design", "vi")

# (wrong_pattern, replacement) — order matters for overlapping rules
GLOSSARY_FIXES: list[tuple[str, str]] = [
    (r"\{chiều rộng=\d+\}", ""),
    (r"\{width=\d+\}", ""),
    # MT left literal \w (broken "with" / punctuation)
    (r"chuyên gia \\w ở", "chuyên gia ở"),
    (r"khách sạn \\w 5000", "khách sạn với 5000"),
    (r"máy chủ email \\w bằng", "máy chủ email bằng"),
    (r"thư mục \\w phân trang", "thư mục kèm phân trang"),
    (r"mỗi ngày \\w 10%", "mỗi ngày với 10%"),
    (r"bảng quan hệ \\w bốn", "bảng quan hệ với bốn"),
    (r"chứng chỉ SSL \\w", "chứng chỉ SSL"),
    (r" \\w ", " với "),
    (r" \\w<", "<"),
    (r" \\w<br", "<br"),
    # Speaker labels (interview Q&A)
    (r"\bTôi:", "I:"),
    # Repeated section titles from MT
    (r"Ước tính mặt sau của phong bì", "Ước tính back-of-the-envelope"),
    (r"Ước tính cuối phong bì", "Ước tính back-of-the-envelope"),
    (r"<strong>Mặt sau của phong bì</strong>", "<strong>Back-of-the-envelope</strong>"),
    (
        r"Bước 2: Đề xuất thiết kế cấp cao và nhận được sự đồng ý",
        "Bước 2: Propose high-level design và thu được buy-in",
    ),
    # MT article artifact
    (r"\bMỘT <strong>", "<strong>"),
    (r"<th>MỘT</th>", "<th>A</th>"),
    (r"<li><strong>Dịch vụ bưu chính:</strong>", "<li><strong>Post Service:</strong>"),
    (r"không quốc tịch", "stateless"),
    (r"phụ/pub", "pub/sub"),
    (r"thành phần pub/sub của redis", "Redis pub/sub"),
    # Typos / product names
    (r"\bElaticsearch\b", "Elasticsearch"),
    (r"\bBản đồ Google\b", "Google Maps"),
    (r"\bkêu lên\b", "Yelp"),
    (r"\bTwitter Snowflake\b", "Twitter Snowflake"),
    (r"\bbông tuyết trên Twitter\b", "Twitter Snowflake"),
    (r"\bMáy chủ bán vé\b", "Ticket Server"),
    # Event sourcing / Raft
    (r"Tìm nguồn cung ứng sự kiện hiệu suất cao đáng tin cậy", "Event sourcing hiệu suất cao đáng tin cậy"),
    (r"Tìm nguồn cung ứng sự kiện hiệu suất cao", "Event sourcing hiệu suất cao"),
    (r"Nguồn cung ứng sự kiện phân tán", "Event sourcing phân tán"),
    (r"<strong>Tìm nguồn cung ứng sự kiện</strong>", "<strong>Event sourcing</strong>"),
    (r"\btìm nguồn cung ứng sự kiện\b", "event sourcing"),
    (r"\bnguồn cung ứng sự kiện\b", "event sourcing"),
    (r"\bTrưởng bè\b", "Raft leader"),
    (r"\bnhóm bè\b", "Raft group"),
    (r"\bbản sao của bè\b", "Raft replication"),
    (r"\bngười dẫn đầu-người theo dõi\b", "leader-follower"),
    # Quorum / KV store
    (r"Sự đồng thuận của đại biểu", "Quorum consensus"),
    (r"kích thước đại biểu", "quorum size"),
    (r"yêu cầu đại biểu", "yêu cầu quorum"),
    (r"<strong>Đại biểu cẩu thả:?</strong>", "<strong>Sloppy quorum:</strong>"),
    (r"<strong>Bàn giao gợi ý:?</strong>", "<strong>Hinted handoff:</strong>"),
    (r"khóa tạm thời", "idempotency key"),
    # Idempotency — MT mistranslates as bình thường/tạm thời/bình đẳng
    (r"mục đích tạm thời", "mục đích idempotency"),
    (r"cơ chế bình thường - một thuộc tính", "cơ chế idempotency — một thuộc tính"),
    (r"cơ chế bình thường", "cơ chế idempotency"),
    (r"Tính tạm thời", "Idempotency"),
    (r"Tính bình thường", "Idempotency"),
    (r"Tính bình đẳng", "Idempotency"),
    (r"chìa khóa bình thường", "idempotency key"),
    (r"khóa bình thường", "idempotency key"),
    (r"API tạm thời", "Idempotent API"),
    (r"cùng một lần hai lần", "cùng một nonce hai lần"),
    (r"xử lý kết quả tổng hợp một cách bình thường", "xử lý kết quả tổng hợp theo cách idempotent"),
    # API / doc labels (follow-up review)
    (r"Phản hồi mẫu", "Sample response"),
    (r"Phản hồi ví dụ", "Sample response"),
    (r"<strong>Xây dựng phản hồi:</strong>", "<strong>Response Construction:</strong>"),
    (r"Xây dựng phản hồi", "Response Construction"),
    (r"replication coding", "erasure coding"),
    (r"sự hòa hợp giữa hệ thống bên trong và bên ngoài", "reconciliation (đối soát) giữa hệ thống nội bộ và bên ngoài"),
    (r"\bsợi dây\b", "string"),
    (r"thiết kế bài viết của mình xoay quanh việc phân khối", "thiết kế các write xoay quanh batching"),
    (r"Bài viết chỉ được chấp nhận bởi phân đoạn mới nhất", "Chỉ segment mới nhất nhận write"),
    (r"để offset cho thông lượng ghi đĩa tuần tự", "để bù cho thông lượng ghi tuần tự"),
    (r"\bchúng I\b", "chúng ta"),
    (r"thăm dò polling", "polling"),
    (r"Việc bỏ phiếu", "Polling"),
    (r"tần suất bỏ phiếu", "tần suất polling"),
    (r"nhà xuất bản dữ liệu thị trường", "market data publisher"),
    (r"lưu trữ đồ vật", "object storage"),
    (r"\bđồ vật\b", "object"),
    (r"<strong>Phiên bản</strong>", "<strong>Versioning</strong>"),
    (r"trong một nhóm\. Chứa", "trong một bucket. Chứa"),
    (r"trong cùng một nhóm\.", "trong cùng một bucket."),
    (r"<strong>Người mẫu</strong>", "<strong>Models</strong>"),
    # Rate limiting / components
    (r"\bGiới hạn tỷ lệ\b", "Rate limiting"),
    (r"\bgiới hạn tỷ lệ\b", "rate limiting"),
    (r"<h3>Linh kiện</h3>", "<h3>Components</h3>"),
    (r"<h4>Linh kiện</h4>", "<h4>Components</h4>"),
    (r"<strong>Linh kiện</strong>", "<strong>Components</strong>"),
  # State / messaging
    (r"Dịch vụ không quốc tịch", "Dịch vụ stateless"),
    (r"đăng ký xuất bản", "pub/sub"),
    (r"Điểm duy nhất của sự thất bại", "single point of failure"),
    # Search / trie
    (r"<strong>Triệu DB</strong>", "<strong>Trie DB</strong>"),
    (r"\bbộ ba\b", "trie"),
    (r"\bbản dùng thử\b", "trie"),
    (r"xây dựng tri\.", "xây dựng trie."),
    # News feed / fanout
    (r"<strong>Dịch vụ bưu chính</strong>", "<strong>Post Service</strong>"),
    (r"<strong>dịch vụ hâm mộ</strong>", "<strong>Fanout Service</strong>"),
    (r"Các cửa hàng cache", "Cache"),
    # Crawler
    (r"Biên giới URL", "URL Frontier"),
    (r"Chủ đề công nhân", "worker thread"),
    # Storage / email
    (r"<strong>Tìm kiếm cửa hàng</strong>", "<strong>Search store</strong>"),
    (r"Tốc độ load balancer giới hạn", "Load balancer giới hạn tốc độ"),
    # S3
    (r"<strong>Xô</strong>", "<strong>Bucket</strong>"),
    (r"<strong>Sự vật</strong>", "<strong>Object</strong>"),
    (r"độ bền 6 giây", "độ bền 6 nines"),
    (r"độ bền 11 giây", "độ bền 11 nines"),
    (r"hiệu suất niêm yết", "hiệu suất listing"),
    # Payment
    (r"<strong>Hòa giải</strong>", "<strong>Reconciliation</strong>"),
    (r"Luồng thanh toán - hệ thống thanh toán nhận tiền", "Pay-in flow — hệ thống thanh toán nhận tiền"),
    (r"Luồng thanh toán - hệ thống thanh toán gửi tiền", "Pay-out flow — hệ thống thanh toán gửi tiền"),
    (r"<h3><strong>Luồng thanh toán</strong></h3>", "<h3><strong>Pay-in flow</strong></h3>",),
    # Stream processing
    (r"bồn rửa đồng bộ", "synchronous sink"),
    (r"<h3><strong>trộn</strong></h3>", "<h3><strong>Batching</strong></h3>"),
    # Trading (stock exchange)
    (r"sổ đặt hàng", "order book"),
    (r"cửa hàng sự kiện", "event store"),
    (r"người quản lý đơn hàng", "order manager"),
    # Misc domain
    (r"Ủng hộ hoạt động đọc hiệu quả", "Hỗ trợ đọc hiệu quả"),
    (r"Độ phân giải băm \+ va chạm", "Hash + collision resolution"),
    (r"tải lên bị xáo trộn", "tải lên bị gián đoạn"),
    (r"<strong>Tứ giác</strong>", "<strong>Quadtree</strong>"),
    (r"đồ thị chu kỳ có hướng", "đồ thị có hướng không chu trình (DAG)"),
    (r"\bthùng chứa\b", "container"),
    (r"Bộ sưu tập số liệu", "Metrics collection"),
    (r"cửa hàng đang vận hành", "operational store"),
    (r"cắt đứt quan hệ", "tie-break"),
    (r"tập hợp được sắp xếp", "Redis sorted set"),
    (r"đơn hàng toàn cầu", "global ordering"),
    (r"phòng_loại_tỷ lệ", "room_type_rate"),
    (r"Chúng ta nên ủng hộ những điều đó", "Chúng ta nên hỗ trợ những điều đó"),
    (r"Chia tỷ lệ dọc", "Scale dọc (vertical scaling)"),
    (r"Chia tỷ lệ ngang", "Scale ngang (horizontal scaling)"),
    (r"\bChia tỷ lệ\b", "Scale"),
    (r"\bbộ giới hạn tốc độ\b", "rate limiter"),
    (r"\bBộ giới hạn tốc độ\b", "Rate limiter"),
    (r"Cửa hàng khóa-giá trị", "Key-Value Store"),
    (r"Cửa hàng cột", "Column Store"),
    (r"Cửa hàng tài liệu", "Document Store"),
    (r"Cơ sở dữ liệu đồ thị", "Graph Database"),
    (r"Thiết lập máy chủ đơn", "Kiến trúc single server"),
    (r"cơ sở người dùng", "lượng người dùng"),
    (r"sàng lọc", "tinh chỉnh"),
    (r"kiến ​​trúc", "kiến trúc"),
    (r"Yêu cầu HTTP", "HTTP request"),
    (r"Luồng yêu cầu", "Luồng request"),
    (r"kiến ​​thức", "kiến thức"),
    (r"kiến​ thức", "kiến thức"),
    (r"ý kiến ​​​​", "polling "),
    (r"thăm dò ý kiến", "polling"),
    (r"Cửa hàng KV", "Key-Value store"),
    (r"Cửa hàng <code>", "Bảng mapping <code>"),
    (r"Cửa hàng đính kèm", "Attachment store"),
    (r"Trích xuất kiến thức", "Trích xuất knowledge"),
    (r"bộ đệm", "cache"),
    (r"Bộ đệm", "Cache"),
    (r"DoS", "DoS"),
    (r"\bAPI\b", "API"),
    (r"\bcân bằng tải\b", "load balancer"),
    (r"\bCân bằng tải\b", "Load balancer"),
    (r"\bbộ cân bằng tải\b", "load balancer"),
    (r"\bphân đoạn\b(?=.*shard)", "sharding"),
    (r"\bSharding\b", "sharding"),
    (r"\bBộ nhớ đệm\b", "Cache"),
    (r"\bbộ nhớ đệm\b", "cache"),
    (r"\bMạng phân phối nội dung\b", "CDN"),
    (r"\bmạng phân phối nội dung\b", "CDN"),
    (r"\btruy vấn mỗi giây\b", "QPS"),
    (r"\bTruy vấn mỗi giây\b", "QPS"),
    (r"\bchủ\s*-\s*tớ\b", "master-slave"),
    (r"\bChủ\s*-\s*Tớ\b", "Master-slave"),
    (r"\bchủ tớ\b", "master-slave"),
    (r"\bChủ tớ\b", "Master-slave"),
    (r"\bđiểm lỗi duy nhất\b", "single point of failure"),
    (r"\bĐiểm lỗi duy nhất\b", "Single point of failure"),
    (r"\bSPOF\b", "SPOF"),
    (r"\bhash nhất quán\b", "consistent hashing"),
    (r"\bHash nhất quán\b", "Consistent hashing"),
    (r"\bgiới hạn tốc độ\b", "rate limiter"),
    (r"\bGiới hạn tốc độ\b", "Rate limiter"),
    (r"\bkhông trạng thái\b", "stateless"),
    (r"\bKhông trạng thái\b", "Stateless"),
    (r"\bhigh availability\b", "high availability"),
    (r"\bTính khả dụng cao\b", "High availability (HA)"),
    (r"\btính khả dụng cao\b", "high availability"),
    (r"\bmessage queue\b", "message queue"),
    (r"\bHàng đợi tin nhắn\b", "Message queue"),
    (r"\bhàng đợi tin nhắn\b", "message queue"),
    (r"\bresharding\b", "resharding"),
    (r"\bResharding\b", "Resharding"),
    (r"\bde-normalize\b", "de-normalize"),
    (r"\bphi cấu trúc\b", "unstructured"),
    (r"\bPhần\s+(\d+)\s*:", r"Phần \1:"),
    (r"\bMục\s+(\d+)\s*:", r"Phần \1:"),
    (r"\bChương\s+(\d+)\s*:", r"Chương \1:"),
    (r"&amp;amp;", "&amp;"),
    (r"&#39;", "'"),
    (r"\s+/\s+giây", "/giây"),
    (r"~\s*(\d)", r"~\1"),
    (r" ,", ","),
    (r" \.", "."),
    (r" \?", "?"),
]

# Prefer English jargon over literal Vietnamese (OpenAI review: keep is OK)
KEEP_ENGLISH_FIXES: list[tuple[str, str]] = [
    (r"<h3>Thành phần bổ sung</h3>", "<h3>Additional components</h3>"),
    (r"<h3>Thành phần</h3>", "<h3>Components</h3>"),
    (r"<h4>Thành phần</h4>", "<h4>Components</h4>"),
    (r"<h2>Thành phần hệ thống</h2>", "<h2>System components</h2>"),
    (r"\bNHẠC POP\b", "POP3"),
    (r"\bnhân viên lấy sự kiện\b", "worker lấy event"),
    (r"\bnhân viên xử lý thư\b", "mail worker"),
    (r"\bnhân viên gửi đi\b", "outbound SMTP worker"),
    (r"\bnhân viên tác vụ\b", "task worker"),
    (r"\bTrình lập lịch tác vụ\b", "Task scheduler"),
    (r"\bchọn tác vụ/nhân viên tối ưu\b", "chọn task/worker tối ưu"),
    (r"\bhướng dẫn nhân viên tác vụ\b", "dispatch tới task worker"),
    (r"\bCác nhân viên nhiệm vụ\b", "Các task worker"),
    (r"\bkho đối tượng\b", "object store"),
    (r"\bKho đối tượng\b", "Object store"),
    (r"\bcơ sở dữ liệu\b", "database"),
    (r"\bCơ sở dữ liệu\b", "Database"),
    (r"\bmáy chủ web\b", "web server"),
    (r"\bMáy chủ web\b", "Web server"),
    (r"\bmáy chủ email\b", "mail server"),
    (r"\bMáy chủ email\b", "Mail server"),
    (r"\bmáy chủ thư\b", "mail server"),
    (r"\bMáy chủ thư\b", "Mail server"),
    (r"\bmáy chủ websocket\b", "WebSocket server"),
    (r"\bMáy chủ websocket\b", "WebSocket server"),
    (r"\bmáy chủ API\b", "API server"),
    (r"\bMáy chủ API\b", "API server"),
    (r"\bmáy chủ thời gian thực\b", "realtime server"),
    (r"\bphân vùng\b", "partition"),
    (r"\bPhân vùng\b", "Partition"),
    # API docs — keep standard English labels
    (r"<h3>Điểm cuối API</h3>", "<h3>API endpoints</h3>"),
    (r"<th>Điểm cuối API</th>", "<th>API endpoint</th>"),
    (r"<strong>Thông số yêu cầu</strong>", "<strong>Request parameters</strong>"),
    (r"Tham số truy vấn:", "Query parameters:"),
    (r"Tham số truy vấn", "Query parameters"),
    (r"tham số truy vấn", "query parameters"),
    (r"Tham số yêu cầu", "Request parameters"),
    (r"tham số đầu vào", "input parameters"),
    (r"điều chỉnh tham số", "tuning parameters"),
    (r"các tham số", "parameters"),
    (r"thông số thời gian chờ và thử lại", "timeout và retry parameters"),
    (r"hai thông số", "hai parameters"),
    (r"<strong>Thông số:</strong>", "<strong>Parameters:</strong>"),
    (r"<strong>Điểm cuối:</strong>", "<strong>Endpoint:</strong>"),
    (r"<p>Thông số:<br/>", "<p>Parameters:<br/>"),
    (r"Thông số:<br/>", "Parameters:<br/>"),
    (r"Thông số:", "Parameters:"),
    (r"Điểm cuối:", "Endpoint:"),
    (r"điểm cuối số liệu", "metrics endpoint"),
    (r"điểm cuối dịch vụ", "service endpoint"),
    (r"điểm cuối http", "HTTP endpoint"),
    (r"các điểm cuối", "các endpoint"),
    (r"hai điểm cuối", "hai endpoint"),
    (r"điểm cuối", "endpoint"),
    (r"Điểm cuối", "Endpoint"),
    (r"\(xác thực\)", "(auth)"),
    (r"đăng văn bản", "text post"),
    # Push/pull models & push notifications — keep English (avoid mô hình đẩy/kéo)
    (r"Dịch vụ thông báo đẩy của Apple \(APNS\)", "Apple Push Notification service (APNS)"),
    (r"Dịch vụ thông báo đẩy của Apple", "Apple Push Notification service (APNS)"),
    (r"Thông báo đẩy iOS", "iOS push notification"),
    (r"Thông báo đẩy của Android", "Android push notification"),
    (r"<strong>Thông báo đẩy</strong>", "<strong>Push notification</strong>"),
    (r"Thông báo đẩy", "Push notification"),
    (r"thông báo đẩy", "push notification"),
    (r"Dịch vụ thông báo đẩy", "Push notification service"),
    (r"gửi thông báo đẩy", "gửi push notification"),
    (r"cho thông báo đẩy", "cho push notification"),
    (r"\(đẩy, SMS", "(push, SMS"),
    (r"cổng đẩy cho mô hình kéo", "push gateways cho pull model"),
    (r"sử dụng mô hình đẩy hay kéo", "dùng push hay pull model"),
    (r"mô hình đẩy hay kéo", "push hay pull model"),
    (r"Sử dụng mô hình đẩy cho hầu hết người dùng và mô hình kéo cho",
     "Dùng push model cho hầu hết user và pull model cho"),
    (r"với mô hình đẩy, các dịch vụ", "với push model, services"),
    (r"với mô hình đẩy, broker", "với push model, broker"),
    (r"với mô hình kéo, consumer", "với pull model, consumer"),
    (r"Mô hình kéo phù hợp hơn", "Pull model phù hợp hơn"),
    (r"chọn mô hình kéo", "chọn pull model"),
    (r"Đây là mô hình kéo", "Đây là pull model"),
    (r"<strong>Mô hình đẩy</strong>", "<strong>Push model</strong>"),
    (r"<strong>Mô hình kéo</strong>", "<strong>Pull model</strong>"),
    (r"mô hình đẩy", "push model"),
    (r"mô hình kéo", "pull model"),
    (r"kiến trúc kéo", "pull architecture"),
    (r"kiến trúc đẩy", "push architecture"),
    (r"Phương pháp kéo", "Pull method"),
    (r"Phương pháp đẩy", "Push method"),
    (r"phương pháp đẩy", "push method"),
    (r"phương pháp kéo", "pull method"),
    (r"giữa đẩy và kéo", "giữa push và pull"),
    (r"kéo hoặc đẩy", "pull hoặc push"),
    (r"\| Kéo \| Đẩy \|", "| Pull | Push |"),
    (r"Kéo thắng", "Pull wins"),
    (r"Đẩy thắng", "Push wins"),
    (r"thao tác kéo", "pull operation"),
    (r"khoảng thời gian kéo", "pull interval"),
    (r"yêu cầu đẩy", "push requests"),
    (r"tác nhân đẩy", "push agent"),
    (r"producer đẩy tin nhắn", "producer push messages"),
    (r"Đẩy bài viết lên", "Push posts lên"),
    (r"Kéo bài viết tại", "Pull posts tại"),
    (r"Metrics collector đẩy dữ liệu metric", "Metrics collector push metrics data"),
    (r"đẩy dữ liệu đó vào time-series DB", "push data vào time-series DB"),
    # Round 3 — keep English jargon (broad sweep; longer phrases first)
  # Metadata / fetch
    (r"<strong>Tương tác người dùng:</strong>", "<strong>User interaction:</strong>"),
    (r"Tương tác người dùng", "User interaction"),
    (r"kho lưu trữ siêu dữ liệu", "metadata store"),
    (r"Kho lưu trữ siêu dữ liệu", "Metadata store"),
    (r"Kho siêu dữ liệu", "Metadata store"),
    (r"kho siêu dữ liệu", "metadata store"),
    (r"database siêu dữ liệu", "metadata database"),
    (r"<h3>database siêu dữ liệu</h3>", "<h3>Metadata database</h3>"),
    (r"<h3><strong>database siêu dữ liệu</strong></h3>", "<h3><strong>Metadata database</strong></h3>"),
    (r"<strong>database siêu dữ liệu và cache:</strong>", "<strong>Metadata database và cache:</strong>"),
    (r"<strong>database siêu dữ liệu:</strong>", "<strong>Metadata database:</strong>"),
    (r"Sao chép database siêu dữ liệu", "Metadata database replication"),
    (r"Mô hình dữ liệu siêu dữ liệu", "Metadata data model"),
    (r"lưu trữ siêu dữ liệu", "metadata storage"),
    (r"Lưu trữ siêu dữ liệu", "Metadata storage"),
    (r"Tải lên siêu dữ liệu", "Upload metadata"),
    (r"Tìm nạp siêu dữ liệu", "Fetch metadata"),
    (r"tìm nạp siêu dữ liệu", "fetch metadata"),
    (r"siêu dữ liệu", "metadata"),
    (r"Siêu dữ liệu", "Metadata"),
    (r"Trình thu thập số liệu tìm nạp", "Metrics collector fetch"),
    (r"Trình quản lý cảnh báo tìm nạp", "Alert manager fetch"),
    (r"Tìm nạp Geohash lân cận", "Fetch neighboring geohashes"),
    (r"Tìm nạp ID doanh nghiệp", "Fetch business IDs"),
    (r"Thuật toán tìm nạp", "Fetch algorithm"),
    (r"tìm nạp email", "fetch email"),
    (r"tìm nạp các", "fetch các"),
    (r"Tìm nạp", "Fetch"),
    (r"tìm nạp", "fetch"),
  # Consistent hashing / sharding / replication
    (r"vòng băm nhất quán", "consistent hash ring"),
    (r"hàm băm nhất quán", "consistent hashing"),
    (r"Hàm băm nhất quán", "Consistent hashing"),
    (r"băm nhất quán", "consistent hashing"),
    (r"Băm nhất quán", "Consistent hashing"),
    (r"kho lưu trữ khóa-giá trị phân tán", "distributed key-value store"),
    (r"kho lưu trữ khóa-giá trị", "key-value store"),
    (r"<strong>kho khóa-giá trị</strong>", "<strong>Key-value store</strong>"),
    (r"kho khóa-giá trị", "key-value store"),
    (r"Kho khóa-giá trị", "Key-value store"),
    (r"Lưu trữ khóa-giá trị", "Key-value storage"),
    (r"sao chép và phân mảnh", "replication và sharding"),
    (r"Sao chép database", "Database replication"),
    (r"sao chép database", "database replication"),
    (r"nhóm sao chép", "replica group"),
    (r"mã hóa sao chép", "replication coding"),
    (r"phân mảnh database", "database sharding"),
    (r"phân mảnh mạng", "network partition"),
    (r"phân mảnh", "sharding"),
    (r"Phân mảnh", "Sharding"),
    (r"sơ đồ phân mảnh", "sharding scheme"),
  # Queues / DLQ
    (r"Hàng đợi thư chết", "Dead letter queue"),
    (r"hàng đợi thư chết", "dead letter queue"),
    (r"Hàng đợi thử lại", "Retry queue"),
    (r"hàng đợi thử lại", "retry queue"),
    (r"Hàng đợi sao lưu ngoại tuyến", "Offline backup queue"),
    (r"hàng đợi lỗi", "error queue"),
    (r"hàng đợi trễ", "delay queue"),
    (r"hàng đợi gửi đi", "outbound queue"),
  # Named services (component labels)
    (r"<strong>Dịch vụ thanh toán</strong>", "<strong>Payment service</strong>"),
    (r"Dịch vụ thanh toán", "Payment service"),
    (r"<strong>Dịch vụ truy vấn</strong>", "<strong>Query service</strong>"),
    (r"Dịch vụ truy vấn", "Query service"),
    (r"dịch vụ truy vấn", "query service"),
    (r"<h3>Dịch vụ thông báo</h3>", "<h3>Notification Service</h3>"),
    (r"<strong>Dịch vụ thông báo:</strong>", "<strong>Notification Service:</strong>"),
    (r"Dịch vụ thông báo", "Notification Service"),
    (r"<strong>Dịch vụ API</strong>", "<strong>API service</strong>"),
    (r"Dịch vụ API", "API service"),
    (r"<strong>Dịch vụ stateless:</strong>", "<strong>Stateless services:</strong>"),
    (r"<strong>Dịch vụ có trạng thái:</strong>", "<strong>Stateful services:</strong>"),
    (r"<strong>Dịch vụ đặt chỗ</strong>", "<strong>Reservation service</strong>"),
    (r"<strong>Dịch vụ khách sạn</strong>", "<strong>Hotel service</strong>"),
    (r"<strong>Dịch vụ quản lý khách sạn</strong>", "<strong>Hotel management service</strong>"),
    (r"<strong>Dịch vụ kích hoạt:</strong>", "<strong>Trigger service:</strong>"),
    (r"Dịch vụ kích hoạt", "Trigger service"),
    (r"<strong>Dịch vụ thu thập dữ liệu:</strong>", "<strong>Data collection service:</strong>"),
    (r"<h3>Dịch vụ thu thập dữ liệu</h3>", "<h3>Data collection service</h3>"),
    (r"Dịch vụ thu thập dữ liệu", "Data collection service"),
    (r"<strong>Dịch vụ định vị</strong>", "<strong>Geolocation service</strong>"),
    (r"<strong>Dịch vụ điều hướng</strong>", "<strong>Routing service</strong>"),
  # Sync / client / worker / infra
    (r"xung đột đồng bộ hóa", "sync conflict"),
    (r"Xung đột đồng bộ hóa", "Sync conflict"),
    (r"Tốc độ đồng bộ nhanh", "Fast sync"),
    (r"đồng bộ hóa bị trì hoãn", "sync bị trì hoãn"),
    (r"đồng bộ hóa tệp", "file sync"),
    (r"đồng bộ hóa các thay đổi database", "sync database changes"),
    (r"thách thức đồng bộ hóa", "sync challenges"),
    (r"chi phí đồng bộ hóa", "chi phí sync"),
    (r"đồng bộ hóa hiệu quả", "sync hiệu quả"),
    (r"được đồng bộ hóa", "được sync"),
    (r"đồng bộ hóa", "sync"),
    (r"Đồng bộ hóa", "Sync"),
    (r"cổng máy khách", "client gateway"),
    (r"Cổng máy khách", "Client gateway"),
    (r"phía máy khách", "phía client"),
    (r"Máy khách", "Client"),
    (r"máy khách", "client"),
    (r"<strong>Công nhân:</strong>", "<strong>Worker:</strong>"),
    (r"Công nhân xử lý", "Worker xử lý"),
    (r"Công nhân", "Worker"),
    (r"giới hạn tỷ lệ", "rate limiting"),
    (r"Giới hạn tỷ lệ", "Rate limiting"),
    (r"<strong>Đại lý thu thập</strong>", "<strong>Collection agent</strong>"),
    (r"tường lửa", "firewall"),
    (r"Tường lửa", "Firewall"),
    (r"điều phối viên nhóm consumer", "consumer group coordinator"),
    (r"Điều phối viên nhóm consumer", "Consumer group coordinator"),
    (r"điều phối viên broker", "broker coordinator"),
    (r"Điều phối viên", "Coordinator"),
    (r"điều phối viên", "coordinator"),
    (r"<strong>Chặn tải xuống:</strong>", "<strong>Block download:</strong>"),
    (r"<strong>Cò súng:</strong>", "<strong>Long polling:</strong>"),
  # Replication / replica / storage (round 3b)
    (r"kiến trúc bản sao chính", "primary-replica architecture"),
    (r"bản sao đã đọc", "read replica"),
    (r"bản sao đọc", "read replica"),
    (r"bộ lưu trữ đối tượng", "object store"),
    (r"Bộ lưu trữ đối tượng", "Object store"),
    (r"Thành phần cốt lõi", "Core components"),
    (r"Thành phần kích thước", "Component size"),
    (r"Thành phần này", "Component này"),
    (r"tính năng sao chép", "replication"),
    (r"kế hoạch sao chép", "replica distribution plan"),
    (r"sao chép chậm", "slow replication"),
    (r"sao chép dữ liệu", "replicate data"),
    (r"việc sao chép dữ liệu", "data replication"),
    (r"được sao chép giữa các nút", "được replicate giữa các node"),
    (r"partition được sao chép", "partition được replicate"),
    (r"thông điệp được sao chép", "messages được replicate"),
    (r"Tin nhắn được sao chép", "Messages được replicate"),
    (r"sao chép thêm", "extra copy overhead"),
    (r"bị sao chép thêm", "bị duplicate"),
    (r"đủ số lượng bản sao", "đủ replica trong ISR"),
    (r"phân phối lại bản sao", "re-replicate"),
    (r"việc sao chép để", "replication để"),
    (r"cố gắng sao chép", "replicate"),
    (r"khi sao chép", "khi replicate"),
    (r"database chính và bản sao", "primary DB và replica"),
    (r"các bản sao khác nhau", "các replica khác nhau"),
    (r"nhiều bản sao hơn", "nhiều replica hơn"),
    (r"xóa bản sao partition", "xóa replica partition"),
    (r"từng bản sao", "từng replica"),
    (r"đủ bản sao", "đủ replica"),
    (r"các bản sao", "các replica"),
    (r"một bản sao", "một replica"),
    (r"bản sao chính", "primary replica"),
    (r"bản sao nóng", "hot standby"),
    (r"bản sao/", "standby/"),
    (r"phiên bản sao lưu", "backup instance"),
    (r"sao chép kho sự kiện", "replicate event store"),
    (r"ví dụ về cách sao chép hoạt động", "ví dụ replication hoạt động"),
    (r"phân chia chủ đề theo địa lý", "partition topic theo geography"),
    (r"kích hoạt các chủ đề", "publish tới topics"),
    (r"các chủ đề khác nhau", "các topics khác nhau"),
    (r"phân chia chủ đề", "partition topic"),
    (r"bộ lưu trữ thô", "raw object store"),
    (r"bản sao lưu", "backup copy"),
    (r"sao chép vòng tròn", "circular replication"),
    (r"sao chép đọc", "read replication"),
    (r"được sao chép ở nhiều nút", "được replicate ở nhiều node"),
    (r"Dữ liệu được sao chép", "Data được replicate"),
    (r"sao chép các phiên bản máy chủ", "replicate server instances"),
    (r"bộ lưu trữ chuyên dụng", "dedicated time-series store"),
    (r"bộ lưu trữ KV", "KV store"),
    # Round 4 — full-content sweep (keep standard interview jargon in English)
    (r"\bnhịp tim\b", "heartbeat"),
    (r"\bNhịp tim\b", "Heartbeat"),
    (r"Cơ chế nhịp tim", "Heartbeat mechanism"),
    (r"\bkho lạnh\b", "cold storage"),
    (r"\bKho lạnh\b", "Cold storage"),
    (r"vấn đề điểm nóng", "hotspot problem"),
    (r"vấn đề về điểm nóng", "hotspot problem"),
    (r"các điểm nóng", "hotspots"),
    (r"điểm nóng", "hotspot"),
    (r"topic nóng", "hot topic"),
    (r"cache nóng", "hot cache"),
    (r"đường dẫn quan trọng", "critical path"),
    (r"Nhật ký ghi trước \(WAL\)", "Write-ahead log (WAL)"),
    (r"nhật ký ghi trước \(WAL\)", "write-ahead log (WAL)"),
    (r"Vấn đề về người nổi tiếng", "Celebrity problem"),
    (r"vấn đề người nổi tiếng", "celebrity problem"),
    (r"Tham gia và khử chuẩn hóa", "Join và denormalize"),
    (r"khử chuẩn hóa", "denormalize"),
    (r"đầu vào/đầu ra mỗi giây", "input/output mỗi giây"),
    (r"<strong>Thu gom rác</strong>", "<strong>Garbage collection</strong>"),
    (r"Thu gom rác là quá trình", "Garbage collection là quá trình"),
    (r"Trình thu gom rác", "Garbage collector"),
    (r"trình thu gom rác", "garbage collector"),
    (r"sự kiện thu gom rác", "garbage collection events"),
    # Round 5 — fix capitalized "Fetch" artifact mid-sentence.
    # Component labels start right after ">" (e.g. "<strong>Fetch metadata:"),
    # so " Fetch " (space-bounded) only matches prose usages.
    (r" Fetch ", " fetch "),
]

# Per-file fixes (Kafka terms, trading orders, payment pay-out heading, etc.)
FILE_FIXES: dict[str, list[tuple[str, str]]] = {
    "distributed-message-queue.html": [
        (r"<strong>Lưu trữ dữ liệu</strong>", "<strong>Data storage</strong>"),
        (r"<h3><strong>Lưu trữ dữ liệu</strong></h3>", "<h3><strong>Data storage</strong></h3>"),
        (r"<strong>Dịch vụ điều phối</strong>", "<strong>Coordination service</strong>"),
        (r"dịch vụ điều phối", "coordination service"),
        (r"người điều phối", "coordinator"),
        (r"Người điều phối", "Coordinator"),
        (r"phần bù được tiêu thụ", "consumed offset"),
        (r"chỉ sử dụng phần bù sau", "chỉ commit offset sau"),
        (r"trình phân tích cú pháp", "parser"),
        (r"trình thực thi tập lệnh", "script executor"),
        (r"<strong>Lưu trữ dữ liệu lịch sử</strong>", "<strong>Historical data archive</strong>"),
        (r"kho lưu trữ dung lượng cao", "high-capacity storage"),
        (r"lưu trữ đối tượng", "object storage"),
        (r"consumer Fetch", "Consumer fetches"),
        (r"<strong>Bộ lưu trữ trạng thái</strong>", "<strong>State storage</strong>"),
        (r"Bộ lưu trữ trạng thái", "State storage"),
        (r"lưu trữ trạng thái", "state storage"),
        (r"bộ lưu trữ tạm thời", "temporary store"),
        (r"kế hoạch phân phối bản sao", "replica distribution plan"),
        (r"phân phối bản sao", "replica distribution"),
        (r"bản sao cho một partition", "replica cho partition"),
        (r"bản sao trong ISR", "replica trong ISR"),
        (r"các bản sao", "các replica"),
        (r"một bản sao", "một replica"),
        (r"Lý do có bản sao", "Lý do có replica"),
        (r"đảm bảo đơn hàng phải được giữ nguyên", "đảm bảo thứ tự message phải được giữ nguyên"),
        (r"\bchủ đề\b", "topic"),
        (r"\bChủ đề\b", "Topic"),
        (r"\bphân vùng\b", "partition"),
        (r"\bPhân vùng\b", "Partition"),
        (r"\bnhà môi giới\b", "broker"),
        (r"\bNhà môi giới\b", "Broker"),
        (r"\bMôi giới\b", "Broker"),
        (r"\bmôi giới\b", "broker"),
        (r"\bngười tiêu dùng\b", "consumer"),
        (r"\bNgười tiêu dùng\b", "Consumer"),
        (r"\bnhà sản xuất\b", "producer"),
        (r"\bNhà sản xuất\b", "Producer"),
        (r"\bKhách hàng\b", "Client"),
        (r"\bkhách hàng\b", "client"),
        (r"<strong>bù lại</strong>", "<strong>offset</strong>"),
        (r"\bbù đắp\b", "offset"),
        (r"\btrộn\b", "batching"),
        (r"<strong>Đề tài</strong>", "<strong>Topic</strong>"),
    ],
    "ad-click-aggregation.html": [
        (r"\bngười tiêu dùng\b", "consumer"),
        (r"\bNgười tiêu dùng\b", "Consumer"),
        (r"\bnhà sản xuất\b", "producer"),
        (r"\bNhà sản xuất\b", "Producer"),
        (r"\btrộn\b", "batching"),
        (r"ít nhất một lần là đủ khi chấp nhận được một lượng nhỏ bản sao",
         "at-least-once delivery chấp nhận được một lượng nhỏ duplicate"),
        (r"trình quản lý tài nguyên", "resource manager"),
        (r"Trình quản lý tài nguyên", "Resource manager"),
    ],
    "stock-exchange.html": [
        (r"\bngười đăng ký\b", "subscriber"),
        (r"loại_đơn hàng", "order_type"),
        (r"\bđơn hàng\b", "lệnh"),
        (r"\bĐơn hàng\b", "Lệnh"),
        (r"\bđơn đặt hàng\b", "lệnh"),
        (r"\bđặt hàng\b", "đặt lệnh"),
        (r"đặt hoặc hủy đơn hàng", "đặt hoặc hủy lệnh"),
        (r"đủ tiền trong ví cho đơn hàng", "đủ tiền trong ví cho lệnh"),
        (r"Cả hai đơn hàng đều", "Cả hai lệnh đều"),
        (r"giới hạn tỷ lệ", "rate limiting"),
        (r"\bnhà môi giới\b", "broker"),
        (r"\bNhà môi giới\b", "Broker"),
        (r"cổng khách hàng", "client gateway"),
        (r"Cổng khách hàng", "Client gateway"),
        (r"giữ một bản sao của", "giữ một copy của"),
        (r"bản chính và bản sao", "primary và replica"),
        (r"bản sao nào", "replica nào"),
        (r"dưới dạng bản sao", "dưới dạng standby replica"),
        (r"lệnh thực thi", "execution"),
        (r"Lệnh thực thi", "Execution"),
        (r"Các lệnh thực thi", "Executions"),
        (r"Luồng dữ liệu thị trường", "Market data flow"),
        (r"trình quản lý lệnh", "order manager"),
        (r"trình sắp xếp chuỗi", "sequencer"),
        (r"<h4>Sản phẩm, lệnh, thực hiện</h4>", "<h4>Product, order, execution</h4>"),
        (r"Sản phẩm, lệnh, thực hiện", "Product, order, execution"),
        (r"sổ lệnh", "order book"),
        (r"dữ liệu thị trường", "market data"),
        (r"Dữ liệu thị trường", "Market data"),
        (r"biểu đồ nến", "candlestick chart"),
        (r"người báo cáo", "reporter"),
        (r"Người báo cáo", "Reporter"),
        (r"Khách hàng tương tác", "Client tương tác"),
        (r"cho khách hàng", "cho client"),
        (r"dịch vụ dữ liệu thị trường", "market data service"),
        # Round 4 — event sourcing / leader election / ring buffer
        (r"lược đồ nguồn sự kiện", "event sourcing schema"),
        (r"kho sự kiện", "event store"),
        (r"các điều khoản bầu cử lãnh đạo", "leader election terms"),
        (r"bầu cử người lãnh đạo", "leader election"),
        (r"bầu cử lãnh đạo", "leader election"),
        (r"người dẫn đầu", "leader"),
        (r"người lãnh đạo", "leader"),
        (r"Cache vòng \(còn gọi là cache tròn\)", "Ring buffer (còn gọi là circular buffer)"),
        # API field names (follow-up review)
        (r" \* thực thi -", " * executions -"),
        (r" \* giá thầu -", " * bids -"),
        (r" \* hỏi -", " * asks -"),
        (r" \* nến -", " * candles -"),
        (r"Gấp đôi", "Double"),
        (r"giá mở -", "open -"),
        (r"giá đóng -", "close -"),
        (r"giá thấp -", "low -"),
        (r" \* biểu tượng -", " * symbol -"),
        (r" \* bên -", " * side -"),
        (r" \* giá - giá execution", " * price - execution price"),
        (r" \* số lượng -", " * quantity -"),
        (r" \* chiều sâu -", " * depth -"),
        (r" \* độ phân giải -", " * resolution -"),
        (r"lấy chân nến", "get candles"),
    ],
    "web-crawler.html": [
        (r"URL hạt giống", "Seed URLs"),
        (r"<h3>Trình tải xuống HTML</h3>", "<h3>HTML Downloader</h3>"),
        (r"<strong>Trình tải xuống HTML</strong>", "<strong>HTML Downloader</strong>"),
        (r"Trình tải xuống HTML", "HTML Downloader"),
        (r"Trình phân giải DNS", "DNS Resolver"),
        (r"Trình phân tích nội dung", "Content Parser"),
        (r"<strong>Nội dung đã xem\?:</strong>", "<strong>Content Seen?:</strong>"),
        (r"Nội dung đã xem\?", "Content Seen?"),
        (r"<strong>Lưu trữ nội dung:</strong>", "<strong>Content Storage:</strong>"),
        (r"Lưu trữ nội dung", "Content Storage"),
        (r"Trình trích xuất URL", "URL Extractor"),
        (r"Bộ lọc URL", "URL Filter"),
        (r"<strong>Lưu trữ URL:</strong>", "<strong>URL Storage:</strong>"),
        (r"Lưu trữ URL", "URL Storage"),
        (r"Bộ định tuyến hàng đợi", "Queue Router"),
        (r"Bộ chọn hàng đợi", "Queue Selector"),
        (r"Hàng đợi phía trước", "Front Queue"),
        (r"Hàng đợi quay lại", "Back Queue"),
        (r"trình thu thập thông tin", "web crawler"),
        (r"<strong>Đã thấy URL\?</strong>", "<strong>URL Seen?</strong>"),
        (r"Đã thấy URL\?", "URL Seen?"),
        (r"Các cửa hàng đã truy cập URL", "Stores crawled URLs"),
        (r"trình thu thập dữ liệu web", "web crawler"),
        (r"<strong>trình thu thập dữ liệu web</strong>", "<strong>web crawler</strong>"),
        (r"còn được gọi là nhện", "còn được gọi là spider"),
        (r"<strong>Bẫy nhện:</strong>", "<strong>Spider trap:</strong>"),
        (r"Bẫy nhện", "Spider trap"),
        (r"lập chỉ mục công cụ tìm kiếm", "search engine indexing"),
        (r"quản lý lịch sự", "politeness"),
        (r"<strong>lịch sự</strong>", "<strong>politeness</strong>"),
        (r"<strong>sự ưu tiên</strong>", "<strong>priority</strong>"),
        (r", lịch sự và", ", politeness và"),
    ],
    "google-drive.html": [
        (r"hệ thống nhà xuất bản/người đăng ký", "hệ thống pub/sub"),
        (r"khách hàng ngoại tuyến", "offline client"),
        (r"Khi khách hàng biết", "Khi client biết"),
        (r"khách hàng sẽ", "client sẽ"),
        (r"Khách hàng truy xuất", "Client fetch"),
        (r"Sử dụng bản sao giữa các vùng", "Dùng replica cross-region"),
        (r"cả hai bản sao của cùng một tệp", "hai copies của cùng file"),
        (r"bản sao cục bộ", "local copy"),
        (r"bộ lưu trữ đám mây", "cloud object storage"),
        (r"thông báo cho khách hàng về", "notify client về"),
        (r"\bkhách hàng\b", "client"),
    ],
    "key-value-store.html": [
        (r"Khách hàng giao tiếp", "Client giao tiếp"),
        (r"đồng bộ hóa trên các bản sao", "sync giữa các replica"),
        (r"đồng bộ hóa hai bản sao", "sync hai replica"),
        (r"giữa các bản sao", "giữa các replica"),
        (r"các bản sao", "các replica"),
        (r"hai bản sao", "hai replica"),
        (r"một bản sao", "một replica"),
        (r"Bản sao", "Replica"),
        (r"bản sao", "replica"),
    ],
    "notification-system.html": [
        (r"Công nhân xử lý", "Worker xử lý"),
    ],
    "search-autocomplete.html": [
        (r"<strong>Công nhân:</strong>", "<strong>Worker:</strong>"),
        (r"bộ lưu trữ liên tục", "persistent storage"),
    ],
    "youtube.html": [
        (r"bộ lưu trữ đã chuyển mã", "transcoded storage"),
        (r"bộ lưu trữ tạm thời", "temporary storage"),
        (r"<strong>Bộ tiền xử lý:</strong>", "<strong>Preprocessor:</strong>"),
        (r"<strong>Bộ lập lịch DAG:</strong>", "<strong>DAG scheduler:</strong>"),
        (r"<strong>Trình quản lý tài nguyên:</strong>", "<strong>Resource manager:</strong>"),
        (r"hàng đợi nhiệm vụ trong trình quản lý tài nguyên", "task queue trong resource manager"),
        (r"Hàng đợi nhiệm vụ", "Task queue"),
        (r"Hàng đợi Worker", "Worker queue"),
        (r"<strong>Worker làm nhiệm vụ:</strong>", "<strong>Task worker:</strong>"),
        (r"<strong>Lưu trữ gốc:</strong>", "<strong>Origin storage:</strong>"),
        (r"<strong>Máy chủ chuyển mã:</strong>", "<strong>Transcoding server:</strong>"),
        (r"<strong>Lưu trữ được chuyển mã:</strong>", "<strong>Transcoded storage:</strong>"),
        (r"bộ nhớ gốc", "origin storage"),
        (r"bộ nhớ blob", "blob storage"),
        (r"Bộ nhớ Blob", "Blob storage"),
        (r"Máy chủ chuyển mã", "Transcoding server"),
    ],
    "payment-system.html": [
        (r"trả lại đối tượng hiện có", "trả lại existing object"),
        (r"\bchủ đề\b", "topic"),
        (r"Các thành phần của luồng thanh toán rất giống với luồng thanh toán",
         "Các thành phần của pay-out flow rất giống pay-in flow"),
        (r"\bkhách hàng\b", "client"),
    ],
    "url-shortener.html": [
        (r"<h3>Giới hạn tỷ lệ</h3>", "<h3>Rate limiter</h3>"),
    ],
    "metrics-monitoring.html": [
        (r"<strong>Nguồn số liệu</strong>", "<strong>Metrics source</strong>"),
        (r"<strong>Trình thu thập số liệu</strong>", "<strong>Metrics collector</strong>"),
        (r"Trình thu thập số liệu", "Metrics collector"),
        (r"<strong>database chuỗi thời gian</strong>", "<strong>Time-series database</strong>"),
        (r"database chuỗi thời gian", "time-series database"),
        (r"<strong>Hệ thống trực quan</strong>", "<strong>Visualization system</strong>"),
        (r"Hệ thống trực quan", "Visualization system"),
        (r"người quản lý cảnh báo", "alert manager"),
        (r"<strong>Lưu trữ dữ liệu</strong>", "<strong>Data storage</strong>"),
        (r"Hệ thống lưu trữ dữ liệu", "Data storage system"),
        (r"lấy từ bộ lưu trữ để", "lấy từ metrics store để"),
        (r"Mở rộng quy mô đường truyền số liệu", "Scale metrics transmission pipeline"),
        (r"thu thập số liệu - kéo hoặc đẩy", "metrics collection — pull hoặc push"),
        (r"broker đẩy messages", "broker push messages"),
        (r"đẩy số liệu của họ", "push metrics của họ"),
        (r"đẩy chúng đến bộ thu thập", "push chúng tới metrics collector"),
        (r"có thể đẩy số liệu đến", "có thể push metrics tới"),
        # Follow-up: fix hybrid phrases after prior pass
        (r"Metrics collector Fetch metadata", "Metrics collector fetches metadata"),
        (r"bộ thu thập số liệu", "metrics collector"),
        (r"người thu thập", "collector"),
        (r"metrics collector số liệu", "metrics collector"),
        (r"Tác nhân thu thập số liệu", "Collection agent"),
        (r"DB chuỗi thời gian", "time-series DB"),
        (r"Visualization system hóa", "Visualization system"),
        (r"\| số liệu \| dấu thời gian \| tên máy chủ \|", "| metric | timestamp | hostname |"),
        (r"Giá trị số liệu", "metric_value"),
        (r"hai collector không thu thập cùng một số liệu", "hai collector không thu thập cùng metric"),
        (r"máy chủ lấy số liệu", "pull-based metrics collector"),
        (r"<strong>Bên truy vấn</strong>", "<strong>Query path</strong>"),
        (r"Collection agent từ máy chủ và push chúng tới metrics collector",
         "Collection agent thu thập metrics từ server và push chúng tới metrics collector"),
    ],
    "s3-object-storage.html": [
        (r"<strong>Kho dữ liệu</strong>", "<strong>Data store</strong>"),
        (r"<h3><strong>Kho dữ liệu</strong></h3>", "<h3><strong>Data store</strong></h3>"),
        (r"Kho dữ liệu", "Data store"),
        (r"kho lưu trữ dữ liệu", "data store"),
        (r"mục nhập bộ chứa", "bucket entry"),
        (r"trong một thùng", "trong một bucket"),
        (r"các cửa hàng object", "object stores"),
        (r"cửa hàng object", "object store"),
        (r"kho Object storage", "object store"),
        (r"Kho Object storage", "Object store"),
        (r"vật thể nhỏ và lớn", "object nhỏ và lớn"),
        (r"metadata storage object", "stores object metadata"),
        (r"lập phiên bản", "versioning"),
        (r"tải lên nhiều phần", "multipart upload"),
        (r"replication coding và xóa", "erasure coding"),
        (r"database được phân chia", "sharded database"),
        (r"được phân chia theo bucket", "sharded by bucket"),
        (r", phân chia</p>", ", sharding</p>"),
        (r"<code>filename</code> nơi Object storage", "<code>filename</code> nơi object được lưu trữ"),
        (r"Ví dụ NHẬN yêu cầu fetch một object", "Ví dụ GET request để fetch một object"),
        (r"và Client\.", "và client."),
        (r"trả về Client", "trả về client"),
        (r"cho Client\.", "cho client."),
        (r", Client sẽ gửi", ", client sẽ gửi"),
        (r"\bKhách hàng\b", "Client"),
        (r"\bkhách hàng\b", "client"),
        (r"5 hoặc 7 bản sao", "5 hoặc 7 replica"),
        (r"sao chép nó sang", "replicate sang"),
        (r"sao chép các nút dữ liệu", "replicate data nodes"),
        (r"ba bản sao mang lại", "3 replica mang lại"),
        (r"trong trường hợp có 3 bản sao", "với 3 replica"),
        (r"Việc sao chép yêu cầu", "Replication yêu cầu"),
        (r"thông qua việc sao chép", "qua replication"),
        (r"Trình thu gom rác sao chép", "Garbage collector replicate"),
        (r"Với việc sao chép", "Với replication"),
        (r"Việc sao chép các nút", "Replicate data nodes"),
        (r"việc sao chép", "replication"),
        (r"dữ liệu sơ cấp và bản sao", "primary data và replica"),
        (r"các bản sao", "các replica"),
        (r"một bản sao", "một replica"),
        (r"Lưu trữ đối tượng", "Object storage"),
        (r"lưu trữ đối tượng", "object storage"),
        (r"Bộ lưu trữ đối tượng", "Object store"),
        (r"bộ lưu trữ đối tượng", "object store"),
        (r"Tính bất biến của đối tượng", "Object immutability"),
        (r"các đối tượng", "các object"),
        (r"một đối tượng", "một object"),
        (r"đối tượng", "object"),
        (r"Tạo nhóm,", "Tạo bucket,"),
        (r"đối tượng trong một nhóm", "object trong bucket"),
        (r"đối tượng vào một nhóm", "object vào bucket"),
        (r"bảng nhóm", "bảng bucket"),
        (r"theo nhóm_id", "theo bucket_id"),
        (r"một nhóm có thể", "một bucket có thể"),
        (r"tên nhóm và tên đối tượng", "tên bucket và tên object"),
        (r"quyền chính xác để đọc nhóm", "quyền đọc bucket"),
        (r"Sau khi nhóm được tạo", "Sau khi bucket được tạo"),
        (r"tạo một nhóm có tên", "tạo bucket tên"),
        (r"ID nhóm", "bucket ID"),
    ],
    "distributed-email.html": [
        (r"\bngười tiêu dùng\b", "consumer"),
        (r"\bNgười tiêu dùng\b", "Consumer"),
        (r"metadata email như chủ đề", "email metadata như subject"),
        (r"đến, chủ đề, chưa đọc", "to, subject, unread"),
        (r"chuyển tiếp đến bộ lưu trữ", "forward tới object store"),
    ],
    "digital-wallet.html": [
        (r"hình thức sao chép", "replication"),
        (r"sao chép chúng từ danh sách sự kiện", "replay chúng từ event log"),
        (r"sao chép danh sách trên nhiều nút", "replicate log trên nhiều node"),
        (r"sao chép nó qua các nút khác", "replicate nó qua các node khác"),
        (r"bộ lưu trữ tệp phân tán", "distributed file storage"),
        (r"bộ lưu trữ tệp cục bộ", "local file storage"),
        (r"thay mặt người dùng gửi lệnh và polling phản hồi", "thay mặt người dùng gửi command và poll response"),
    ],
    "hotel-reservation.html": [
        (r"tình trạng sẵn có", "availability"),
        (r"việc sao chép\.", "replication."),
    ],
    "gaming-leaderboard.html": [
        (r"chèn người dùng vào nhóm", "thêm/cập nhật member và score trong sorted set"),
        (r"tạo bản sao Redis", "tạo Redis replica"),
        (r"bản đồ băm", "hash map"),
        (r"danh sách bỏ qua", "skip list"),
        (r"danh sách liên kết được sắp xếp", "sorted linked list"),
        (r"chỉ mục đa cấp", "multi-level index"),
        (r"phân đoạn ghi", "write sharding"),
        (r"lệnh không gian khóa thông tin", "keyspace command"),
        (r"partition băm", "hash partitioning"),
        (r"chỉ mục phụ chung", "global secondary index"),
    ],
    "proximity-service.html": [
        (r"Bước 3: Fetch algorithm các nearby businesses", "Bước 3: Thuật toán fetch nearby businesses"),
        (r"<strong>dịch vụ lân cận</strong>", "<strong>proximity service</strong>"),
        (r"các cột logarit và vĩ độ", "các cột longitude và latitude"),
        (r"Cây tứ giác", "Quadtree"),
        (r"cây tứ giác", "quadtree"),
        (r"xây dựng lại dần dần tứ giác", "xây dựng lại dần dần quadtree"),
        (r"vấn đề ranh giới", "boundary issue"),
        (r"Vấn đề về ranh giới", "Boundary issue"),
        (r"doanh nghiệp lân cận", "nearby businesses"),
        (r"các lưới lân cận", "neighboring grids"),
        (r"geohash lân cận", "neighboring geohashes"),
    ],
    "scaling.html": [
        (r"đa chủ và sao chép vòng tròn", "multi-master và circular replication"),
    ],
    "chat-system.html": [
        (r"<strong>Cơ chế nhịp tim:</strong>", "<strong>Heartbeat mechanism:</strong>"),
        (r"máy chủ hiện diện", "presence server"),
        (r"\bKhách hàng\b", "Client"),
        (r"\bkhách hàng\b", "client"),
    ],
    "news-feed.html": [
        # Headings — mirror EN case-study terms (no VN+EN hybrid)
        (r"<h3>Xuất bản news feed Tìm hiểu sâu</h3>", "<h3>Feed publishing deep dive</h3>"),
        (r"<h3>Xuất bản news feed</h3>", "<h3>Feed publishing</h3>"),
        (r"<h3>Xây dựng news feed</h3>", "<h3>News feed building</h3>"),
        (r"<h3>API news feed</h3>", "<h3>News feed APIs</h3>"),
        (r"<h2>Truy xuất news feed Tìm hiểu sâu</h2>", "<h2>News feed retrieval deep dive</h2>"),
        (r"<strong>Xuất bản news feed:</strong>", "<strong>Feed publishing:</strong>"),
        (r"<strong>Xây dựng news feed:</strong>", "<strong>News feed building:</strong>"),
        (r"<strong>hệ thống cấp tin tức</strong>", "<strong>News feed system</strong>"),
        (r"hệ thống cung cấp tin tức có thể mở rộng", "news feed system có thể scale"),
        (r"dòng thời gian của Twitter", "Twitter timeline"),
        (r"các kết nối của người dùng", "connections của user"),
        (r"đảo ngược thứ tự thời gian", "reverse chronological order"),
        (r"thứ tự thời gian đảo ngược", "reverse chronological order"),
        (r"<strong>Tỉ lệ:</strong>", "<strong>Scale:</strong>"),
        (r"<strong>Đặc trưng:</strong>", "<strong>Features:</strong>"),
        (r"<strong>Tương tác người dùng:</strong>", "<strong>User interaction:</strong>"),
        (r"<strong>Dịch vụ Fanout:</strong>", "<strong>Fanout Service:</strong>"),
        (r"<strong>Dịch vụ thông báo:</strong>", "<strong>Notification Service:</strong>"),
        (r"<strong>Dịch vụ news feed:</strong>", "<strong>News Feed Service:</strong>"),
        (r"dịch vụ news feed", "News Feed Service"),
        (r"<strong>Fanout trên Viết:</strong>", "<strong>Fanout on write:</strong>"),
        (r"<strong>Fanout trên Đọc:</strong>", "<strong>Fanout on read:</strong>"),
        (r"<strong>Phương pháp lai:</strong>", "<strong>Hybrid approach:</strong>"),
        (r"<strong>Cache news feed:</strong>", "<strong>News feed cache:</strong>"),
        (r"Lưu trữ trong cache news feed tin tức", "Store in news feed cache"),
        (r"cache news feed tin tức", "news feed cache"),
        (r"<strong>Cache nội dung:</strong>", "<strong>Content cache:</strong>"),
        (r"<strong>Cache đồ thị xã hội:</strong>", "<strong>Social graph cache:</strong>"),
        (r"<strong>Cache hành động:</strong>", "<strong>Action cache:</strong>"),
        (r"<strong>Cache truy cập:</strong>", "<strong>Counter cache:</strong>"),
        (r"<strong>Tìm nạp ID friends:</strong>", "<strong>Fetch friend IDs:</strong>"),
        (r"<strong>Lọc friends từ cache:</strong>", "<strong>Filter friends from cache:</strong>"),
        (r"<strong>Gửi đến message queue:</strong>", "<strong>Send to message queue:</strong>"),
        (r"các <strong>Fanout Service</strong>", "<strong>fanout service</strong>"),
        (r"truy xuất news feed", "retrieve news feed"),
        (r"Truy xuất news feed", "Retrieve news feed"),
        (r"News feed retrieval API:", "News Feed Retrieval API:"),
        (r"API truy xuất", "retrieval API"),
        (r"Xác thực yêu cầu", "Authenticate requests"),
        (r"Người dùng xuất bản một bài đăng thông qua Post API",
         "User publish post qua Post API"),
        (r"Người dùng yêu cầu news feed của họ thông qua retrieval API",
         "User request news feed qua retrieval API"),
        (r"nguồn cấp dữ liệu", "news feed"),
        (r"nguồn cấp tin tức", "news feed"),
        (r"Nguồn cấp dữ liệu", "News feed"),
        (r"Nguồn cấp tin tức", "News feed"),
        (r"Công nhân Fanout", "Fanout worker"),
        (r"Công nhân truy xuất", "Fanout worker"),
        (r"news feed của Facebook", "Facebook news feed"),
        (r"news feed của Instagram", "Instagram feed"),
        (r"có thể xuất bản bài viết", "có thể publish posts"),
        (r"chuyển hướng đến các dịch vụ", "forward tới services"),
        (r"Tìm nạp ID bài đăng", "Fetch post IDs"),
        (r"một số người bạn nhất định", "một số friends"),
        (r"đối tượng đầy đủ của người dùng và bài đăng", "full user và post objects"),
        (r"\bbạn bè\b", "friends"),
    ],
    "nearby-friends.html": [
        (r"máy chủ ổ cắm web", "WebSocket server"),
        (r"bạn bè ở gần", "nearby friends"),
        (r"Bạn bè ở gần", "Nearby friends"),
        (r"\bbạn bè\b", "friends"),
    ],
    "framework.html": [
        (r"Quy trình xuất bản news feed", "Feed publishing flow"),
        (r"Luồng truy xuất news feed", "News feed retrieval flow"),
        (r"<strong>Hệ thống news feed:</strong>", "<strong>News feed system:</strong>"),
        (r"quá trình xuất bản và truy xuất news feed",
         "feed publishing và news feed retrieval"),
        (r"nguồn cấp dữ liệu", "news feed"),
        (r"nguồn cấp tin tức", "news feed"),
        (r"Hệ thống nguồn cấp tin tức", "News feed system"),
        (r"\bbạn bè\b", "friends"),
    ],
}

SECTION_HEADINGS = {
    "Introduction": "Giới thiệu",
    "Conclusion": "Kết luận",
    "Key Takeaways": "Điểm cần nhớ",
    "Key Objectives": "Mục tiêu chính",
    "Assumptions": "Giả định",
    "Estimations": "Ước lượng",
    "Benefits": "Lợi ích",
    "Challenges": "Thách thức",
    "Workflow": "Luồng hoạt động",
    "Failure Handling": "Xử lý lỗi",
    "Importance": "Tầm quan trọng",
}


def fix_section_headings(html: str) -> str:
    for en, vi in SECTION_HEADINGS.items():
        html = re.sub(
            rf"(<h[23][^>]*>)\s*{re.escape(en)}\s*(</h[23]>)",
            rf"\1{vi}\2",
            html,
            flags=re.I,
        )
        html = re.sub(
            rf"(<h[34][^>]*>)\s*Section\s+(\d+):\s*{re.escape(en)}\s*(</h[34]>)",
            rf"\1Phần \2: {vi}\3",
            html,
            flags=re.I,
        )
    html = re.sub(
        r"(<h2[^>]*>)\s*Section\s+(\d+):\s*([^<]+)(</h2>)",
        r"\1Phần \2: \3\4",
        html,
        flags=re.I,
    )
    return html


def fix_payment_headings(html: str) -> str:
    """Pay-in and pay-out both became 'Pay-in flow' — restore second heading."""
    marker = "<h3><strong>Pay-in flow</strong></h3>"
    idx = html.find(marker)
    if idx == -1:
        return html
    second = html.find(marker, idx + len(marker))
    if second == -1:
        return html
    return (
        html[:second]
        + "<h3><strong>Pay-out flow</strong></h3>"
        + html[second + len(marker) :]
    )


def apply_fixes(text: str, fixes: list[tuple[str, str]]) -> str:
    for pat, repl in fixes:
        text = re.sub(pat, repl, text, flags=re.I if "(?:" not in pat else 0)
    return text


def review_text(text: str, filename: str = "") -> str:
    text = apply_fixes(text, GLOSSARY_FIXES)
    text = apply_fixes(text, KEEP_ENGLISH_FIXES)
    if filename in FILE_FIXES:
        text = apply_fixes(text, FILE_FIXES[filename])
    if filename == "payment-system.html":
        text = fix_payment_headings(text)
    return text


def review_file(path: str) -> bool:
    name = os.path.basename(path)
    orig = open(path, encoding="utf-8").read()
    out = review_text(orig, name)
    out = fix_section_headings(out)
    if out != orig:
        with open(path, "w", encoding="utf-8") as f:
            f.write(out)
        return True
    return False


def main() -> int:
    if not os.path.isdir(VI_DIR):
        print(f"✗ {VI_DIR} not found — run translate first", file=sys.stderr)
        return 1
    changed = 0
    for name in sorted(os.listdir(VI_DIR)):
        if not name.endswith(".html"):
            continue
        if review_file(os.path.join(VI_DIR, name)):
            changed += 1
            print(f"  ✓ reviewed {name}")
        else:
            print(f"  · {name} (no changes)")
    print(f"[review_system_design] updated {changed} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
