"""Chapter metadata for System Design notes (source: liquidslr/system-design-notes)."""

from __future__ import annotations

# folder prefix in source repo -> slug
CHAPTERS: list[dict] = [
    {"n": 1, "folder": "01. Scaling", "slug": "scaling",
     "title": "Scale từ 0 đến hàng triệu người dùng",
     "titleEn": "Scale from Zero to Millions of Users",
     "group": "Nền tảng", "groupEn": "Fundamentals"},
    {"n": 2, "folder": "02. Back Of the Envelope Estimation", "slug": "back-of-envelope",
     "title": "Ước lượng Back-of-the-Envelope",
     "titleEn": "Back-of-the-Envelope Estimation",
     "group": "Nền tảng", "groupEn": "Fundamentals"},
    {"n": 3, "folder": "03. System Design Framework", "slug": "framework",
     "title": "Framework phỏng vấn System Design",
     "titleEn": "A Framework for System Design Interviews",
     "group": "Nền tảng", "groupEn": "Fundamentals"},
    {"n": 4, "folder": "04. Rate Limiter", "slug": "rate-limiter",
     "title": "Thiết kế Rate Limiter",
     "titleEn": "Design a Rate Limiter",
     "group": "Nền tảng", "groupEn": "Fundamentals"},
    {"n": 5, "folder": "05. Consistent Hashing", "slug": "consistent-hashing",
     "title": "Thiết kế Consistent Hashing",
     "titleEn": "Design Consistent Hashing",
     "group": "Nền tảng", "groupEn": "Fundamentals"},
    {"n": 6, "folder": "06. Key-Value Store", "slug": "key-value-store",
     "title": "Thiết kế Key-Value Store",
     "titleEn": "Design a Key-Value Store",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 7, "folder": "07. Unique-Id Generator", "slug": "unique-id-generator",
     "title": "Unique ID Generator phân tán",
     "titleEn": "Design a Unique ID Generator in Distributed Systems",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 8, "folder": "08. URL Shortener", "slug": "url-shortener",
     "title": "Thiết kế URL Shortener",
     "titleEn": "Design a URL Shortener",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 9, "folder": "09. Web Crawler", "slug": "web-crawler",
     "title": "Thiết kế Web Crawler",
     "titleEn": "Design a Web Crawler",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 10, "folder": "10. Notification System", "slug": "notification-system",
     "title": "Thiết kế Notification System",
     "titleEn": "Design a Notification System",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 11, "folder": "11. News Feed System", "slug": "news-feed",
     "title": "Thiết kế News Feed",
     "titleEn": "Design a News Feed System",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 12, "folder": "12. Chat System", "slug": "chat-system",
     "title": "Thiết kế Chat System",
     "titleEn": "Design a Chat System",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 13, "folder": "13. Search Autocomplete", "slug": "search-autocomplete",
     "title": "Thiết kế Search Autocomplete",
     "titleEn": "Design a Search Autocomplete System",
     "group": "Vol 1 — Case study", "groupEn": "Vol 1 — Case studies"},
    {"n": 14, "folder": "14. Youtube", "slug": "youtube",
     "title": "Thiết kế YouTube",
     "titleEn": "Design YouTube",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 15, "folder": "15. Google Drive", "slug": "google-drive",
     "title": "Thiết kế Google Drive",
     "titleEn": "Design Google Drive",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 16, "folder": "16. Proximity Service", "slug": "proximity-service",
     "title": "Proximity Service",
     "titleEn": "Proximity Service",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 17, "folder": "17. Nearby Friends", "slug": "nearby-friends",
     "title": "Nearby Friends",
     "titleEn": "Nearby Friends",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 18, "folder": "18. Google Maps", "slug": "google-maps",
     "title": "Thiết kế Google Maps",
     "titleEn": "Design Google Maps",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 19, "folder": "19. Distributed Message Queue", "slug": "distributed-message-queue",
     "title": "Distributed Message Queue",
     "titleEn": "Distributed Message Queue",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 20, "folder": "20. Metrics Monitoring and Alerting System", "slug": "metrics-monitoring",
     "title": "Metrics Monitoring & Alerting",
     "titleEn": "Metrics Monitoring and Alerting System",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 21, "folder": "21. Ad Click Event Aggregation", "slug": "ad-click-aggregation",
     "title": "Ad Click Event Aggregation",
     "titleEn": "Ad Click Event Aggregation",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 22, "folder": "22. Hotel Reservation System", "slug": "hotel-reservation",
     "title": "Hotel Reservation System",
     "titleEn": "Hotel Reservation System",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 23, "folder": "23. Distributed Email Service", "slug": "distributed-email",
     "title": "Distributed Email Service",
     "titleEn": "Distributed Email Service",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 24, "folder": "24. S3-like Object Storage", "slug": "s3-object-storage",
     "title": "S3-like Object Storage",
     "titleEn": "S3-like Object Storage",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 25, "folder": "25. Real-time Gaming Leaderboard", "slug": "gaming-leaderboard",
     "title": "Real-time Gaming Leaderboard",
     "titleEn": "Real-time Gaming Leaderboard",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 26, "folder": "26. Payment System", "slug": "payment-system",
     "title": "Payment System",
     "titleEn": "Payment System",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 27, "folder": "27.  Digital Wallet", "slug": "digital-wallet",
     "title": "Digital Wallet",
     "titleEn": "Digital Wallet",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
    {"n": 28, "folder": "28. Stock Exchange", "slug": "stock-exchange",
     "title": "Stock Exchange",
     "titleEn": "Stock Exchange",
     "group": "Vol 2 — Case study", "groupEn": "Vol 2 — Case studies"},
]

DEFAULT_SOURCE = "/Users/lamp/Downloads/system-design-notes-main"

# Chapters shown on the site (case studies only — fundamentals excluded from nav).
MANIFEST_CHAPTERS: list[dict] = [c for c in CHAPTERS if "Case study" in c["group"]]
